BookMall/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('myadmin/',include('myadmin.urls')), #include(访问文件路径)  意思是 导入且访问
    path('',include('mybook.urls')), #include(访问文件路径)  意思是 导入且访问

]

mybook/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    #用户登录 注册 退出

    #用户登录
    path('login',userViews.userlogin,name='mybook_login'),
    #用户注册
    path('register',userViews.userregister,name='mybook_register'),
    #用户推出
    path('exit',userViews.userexit,name='mybook_exit'),
    #ajax验证手机号码是否存在
    path('ckphone',userViews.checkphone,name='mybook_ckphone'),
    #手机短信验证码按钮
    path('sendcoke',userViews.sendcoke,name='mybook_sendcoke'),
    #用户中心----个人信息
    path('usercenterinfo',userViews.usercenterinfo,name='mybook_usercenterinfo'),

    #主页面显示
    #商城主页面
    path('',indexViews.index,name='mybook_index'),
    #商城商品列表显示
    path('list',indexViews.list,name='mybook_list'),
    #商城商品详细信息
    path('info',indexViews.info,name='mybook_info'),

    #购物车页面
    path('shoppingcart',cartViews.index,name='mybook_cart'),
    #购物车添加商品
    path('shoppingcartadd',cartViews.addcart,name='mybook_addcart'),
    #购物车删除商品
    path('shoppingcartdel',cartViews.delcart,name='mybook_delcart'),
    #购物车修改商品
    path('shoppingcartup',cartViews.upcart,name='mybook_upcart'),
    #购物车修改选择按钮
    path('shoppingcartcheckedup',cartViews.upchecked,name='mybook_upchecked'),

    #订单
    #提交订单
    path('submitorder',userorderViews.submitorder,name='mybook_suborder'),
    #订单列表页面 支付成功跳转的地址
    path('orderlist',userorderViews.orderlist,name='mybook_orderlist'),

    #收货地址页面
    path('receivingaddress',userViews.receaddress,name='mybook_receaddress'),
    #修改收货地址默认项
    path('upreceselect',userViews.upreceselect,name='mybook_upreceselect'),

    # 支付宝回调地址
    path('pay_result',userorderViews.pay_result,name='mybook_pay_result'),
]

myadmin/models.py
from django.db import models

class Users(models.Model):
    #id,手机号,密码,头像
    phone=models.CharField(max_length=11)
    password=models.CharField(max_length=80)
    face=models.CharField(max_length=100,default='/static/myadmin/images/face/default_face.jpg')
    #昵称,居住地址,性别,身份类型
    nikename=models.CharField(max_length=20,null=True)
    homeaddress = models.CharField(max_length=100,null=True)
    sex = models.CharField(max_length=1,null=True)
    usertype = models.CharField(max_length=50)

class BookType(models.Model):
    #id
    #分类名
    typename=models.CharField(max_length=20)
    #父级id
    fid=models.IntegerField()
    #path
    path=models.CharField(max_length=50)

class Books(models.Model):
    '''
    书名,推荐语,简介,作者
	出版社 出版时间 价格
	所属分类:
	 封面图:
    '''
    #id
    #书名
    bkname=models.CharField(max_length=40)
    #推荐语
    bkreco=models.CharField(max_length=50)
    #简介
    bkbrief=models.CharField(max_length=500)
    #作者
    bkauthor=models.CharField(max_length=30)
    #出版社
    bkpress=models.CharField(max_length=40)
    #出版时间
    bktime=models.DateField()
    #价格
    bkprice=models.FloatField()
    #所属分类
    bktypeid=models.ManyToManyField(to='BookType')


    #封面图 外键1对多      多:图集表 一:图书表
class BooksImgs(models.Model):
    #编号
    #图片url 存放图片
    imgurl=models.ImageField(upload_to='static/myadmin/images/book/')
    #图书id
    imgbkid=models.ForeignKey(to='Books',on_delete=models.CASCADE,)


class ShoppingCart(models.Model):
    #编号
    #图书id
    bid=models.ForeignKey('Books',on_delete=models.CASCADE,)
    #用户id
    uid = models.ForeignKey('Users', on_delete=models.CASCADE, )
    #数量
    number=models.IntegerField()
    #是否选中 0未选中 1选中
    select=models.IntegerField(default=0)

class ReceivingAddress(models.Model):
    #编号
    #收货人
    recename=models.CharField(max_length=30)
    #收货电话
    recephone=models.CharField(max_length=11)
    #收货地址
    receaddress=models.CharField(max_length=100)
    #购买人id
    uid=models.ForeignKey('Users', on_delete=models.CASCADE, )
    # 是否默认 0未选中 1选中
    receselect = models.IntegerField(default=0)

class Order(models.Model):
    #编号(订单号)
    #用户id
    uid=models.ForeignKey('Users', on_delete=models.CASCADE, )
    #收货地址id
    receid=models.ForeignKey('ReceivingAddress',on_delete=models.CASCADE,)
    #支付方式 0货到付款 1微信 2支付宝 3银行卡
    paymethod=models.IntegerField(default=0)
    #订单状态 0 未支付 1已支付 2已发货 3已收货 4取消
    state=models.IntegerField(default=0)
    #订单创建时间
    ordertime=models.DateTimeField(auto_now_add=True) #自动创建当前时间
    #订单支付时间
    paytime=models.DateTimeField(null=True)


class OrderInfo(models.Model):
    #编号
    #订单id
    oid=models.ForeignKey('Order', on_delete=models.CASCADE, )
    #图书id
    bid=models.ForeignKey('Books',on_delete=models.CASCADE,)
    #数量
    number=models.IntegerField()
    # 订单总价
    price = models.FloatField()

mybook/models.py
from django.db import models

# Create your models here.

mybook/views/cartViews.py
import random
from django.contrib.sites import requests
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render,HttpResponse
from django.urls import reverse
from myadmin import models
from django.contrib.auth.hashers import make_password, check_password


#购物车页面
def index(request):
    #接收当前用户
    myuser=request.session.get('myuser')
    #查询当前用户所有购物车信息
    data=models.ShoppingCart.objects.filter(uid=myuser['id'])
    #装入集合
    context={'data':data}
    return render(request,'mybook/cart.html',context)

#购物车添加
def addcart(request):
    #接收post请求及数据
    data=request.POST.dict()
    # 删除token
    data.pop('csrfmiddlewaretoken')
    #接收当前用户
    myuser=request.session.get('myuser')

    #验证用户是否登录
    if not myuser['id']:
        return JsonResponse({'code':1,'msg':'当前用户没有登录'})

    #将data中的id转为对象
    data['bid']=models.Books.objects.get(id=data['bid'])
    data['uid']=models.Users.objects.get(id=myuser['id'])
    try:
        # 判断购物车里是否已经有了这个商品
        zzobj = models.ShoppingCart.objects.filter(bid=data['bid']).count()
        if zzobj:
            return JsonResponse({'code': 3, 'msg': '购物车里已经有此图书,去购物车增加数量即可!'})
        #进行数据库操作
        cartobj=models.ShoppingCart(**data)
        cartobj.save()
        return JsonResponse({'code':0,'msg':'加入购物车成功'})
    except:
        return JsonResponse({'code': 2, 'msg': '加入购物车失败'})

#购物车删除
def delcart(request):
    # 接收购物车信息id
    cartid = request.GET.get('cartid')

    try:
        obj = models.ShoppingCart.objects.get(id=cartid)
        obj.delete()
        return JsonResponse({'code': 0,'msg':'删除成功!'})
    except:
        return JsonResponse({'code': 1,'msg':'删除失败!'})

#是否选中按钮修改
def upchecked(request):
    # 接收购物车信息id
    cartid = request.GET.get('cartid',None)
    # 接收要修改的是否选中
    select = request.GET.get('select')
    try:
        if cartid == None:
            data=models.ShoppingCart.objects.filter().update(select=select)
        else:
            obj=models.ShoppingCart.objects.get(id=cartid)
            obj.select=select
            obj.save()
        return JsonResponse({'code': 0, 'msg': '修改按钮成功'})
    except:
        return JsonResponse({'code': 1, 'msg': '修改按钮失败'})


#购物车信息修改
def upcart(request):
    #接收购物车信息id
    cartid=request.GET.get('cartid')
    #接收要修改的数量
    number=request.GET.get('number')
    try:
        obj=models.ShoppingCart.objects.get(id=cartid)
        obj.number=number
        obj.save()
        return JsonResponse({'code':0,'msg': '修改数量成功'})
    except:
        return JsonResponse({'code': 1,'msg': '修改数量失败'})

mybook/views/indexViews.py
import random
from django.contrib.sites import requests
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render,HttpResponse
from django.urls import reverse
from myadmin import models
from django.contrib.auth.hashers import make_password, check_password

#前台页面跳转
def index(request):
    #左边列表显示
    data=models.BookType.objects.filter(fid=0)
    #添加一个子类图书集合data_son
    for i in data:
        print(i.typename)
        data_son=models.BookType.objects.filter(path__icontains=i.id)
        i.data_son=data_son

    #装入集合
    context={'data':data}
    return render(request, 'mybook/index.html',context)

#商品列表显示
def list(request):
    #下拉列表显示
    data = models.BookType.objects.filter(fid=0)
    #获取图书类别id
    typeid=request.GET.get('typeid')
    #获取查询条件post表单
    textselect=request.GET.get('text_select')
    #判断是否有查询条件
    if textselect!=None:
        data_select=models.Books.objects.filter(bkname__icontains=textselect)
    else:
        data_select=models.Books.objects.filter()
    #查询
    if typeid==None:#没有图书类别
        bkdata=data_select.all().order_by('id')
        pathlist=''
        newbk = models.Books.objects.filter().last()
    else:#有图书类别
        obj=models.BookType.objects.get(id=typeid)
        # 新书推荐
        newbk = models.Books.objects.filter(bktypeid=obj).last()
        #对path进行解释
        list=obj.path[:-1]
        list=list.split(',')
        del list[0]  #删除path第一个0
        list.append(str(obj.id))
        pathlist=[]
        for x in list:
            pathlist.append(models.BookType.objects.get(id=x))
        #通过图书类别查出来的book
        bkdata=data_select.filter(bktypeid=obj).order_by('id')
    # 实例化分页对象(分页的集合,每页显示多少条数据)
    p = Paginator(bkdata, 15)
    # 接收当前页码数 1为默认值
    index_p = request.GET.get('page', 1)
    # 显示当前页的数据
    bkdata = p.page(index_p)
    #装入集合
    context={'data':data,'bkdata':bkdata,'path':pathlist,'text_select':textselect,'newbk':newbk}
    return render(request,'mybook/list.html',context)


#商品详细信息显示
def info(reuqest):
    # 下拉列表显示
    data = models.BookType.objects.filter(fid=0)
    #接收图书id
    id=reuqest.GET.get('id')
    #查询图书信息
    obj=models.Books.objects.get(id=id)
    #新品推荐
    newbk=models.Books.objects.all().order_by('-id')[:2] #逆序排序取头两个数据返回


    #返回字典
    context={'data':data,'obj':obj,'newbk':newbk}
    return render(reuqest,'mybook/info.html',context)

mybook/views/userViews.py
import random

#阿里云
from aliyunsdkcore.client import AcsClient
from aliyunsdkcore.request import CommonRequest


from django.contrib.sites import requests
from django.http import JsonResponse
from django.shortcuts import render,HttpResponse
from django.urls import reverse

from myadmin import models
from django.contrib.auth.hashers import make_password, check_password


#用户中心--主页面(个人信息)
def usercenterinfo(request):
    #接收当前用户
    myuser=request.session.get('myuser')
    userobj=models.Users.objects.get(id=myuser['id'])
    #装入集合
    context={'data':userobj}
    return render(request,'mybook/user_center_info.html',context)

#用户中心--收货地址
def receaddress(request):
    # 接收当前用户信息
    myuser = request.session.get('myuser')
    userobj = models.Users.objects.get(id=myuser['id'])
    if request.method=='POST':
        #接收POST提交的数据
        data=request.POST.dict()
        # 删除token
        data.pop('csrfmiddlewaretoken')
        # 添加当前购买人用户信息
        data['uid']=userobj
        #最多只能拥有两个地址 判断
        if models.ReceivingAddress.objects.filter(uid=userobj).count() >= 2:
            url = reverse('mybook_receaddress')
            return HttpResponse(f'<script>alert("最多只能拥有两个收货地址");location.href="' + url + '" </script>')
        #数据库添加
        obj=models.ReceivingAddress(**data)
        obj.save()
        #跳转
        url = reverse('mybook_receaddress')
        return HttpResponse(f'<script>alert("添加成功");location.href="' + url + '" </script>')
    elif request.method=='GET':
        #查询当前用户的所有收货地址
        data=models.ReceivingAddress.objects.filter(uid=userobj)
        #装入集合
        context={'data':data}
        return render(request,'mybook/user_center_site.html',context)

#修改收货地址默认
def upreceselect(request):
    #接收当前用户
    myuser = request.session.get('myuser')
    userobj = models.Users.objects.get(id=myuser['id'])
    try:
        #把此用户的所有收货地址默认为0
        data=models.ReceivingAddress.objects.filter(uid=userobj)
        for i in data:
            i.receselect=0
            i.save()
        #接收地址id
        id=request.GET.get('receid')
        #修改当前地址 默认属性
        obj=models.ReceivingAddress.objects.get(id=id)
        obj.receselect=1
        obj.save()
        return JsonResponse({'code': 0, 'msg': '修改默认地址成功!'})
    except:
        return JsonResponse({'code': 1, 'msg': '修改默认地址失败!'})

#用户登录
def userlogin(request):
    if request.method=="GET":
        return render(request, 'mybook/login.html')
    elif request.method=="POST":
        #接收post表单
        data=request.POST.dict()
        # 删除token
        data.pop('csrfmiddlewaretoken')
        #查询是否有这个用户
        try:
            obj = models.Users.objects.get(phone=data['phone'])
        except:
            return HttpResponse(f'<script>alert("用户名不存在!");history.back(); </script>')
        #如果存在则验证密码
        if check_password(data['password'],obj.password):
            #登录成功操作 讲用户数据存入session
            request.session['myuser']={'id':obj.id,'phone':obj.phone}
            url = reverse('mybook_index')
            return HttpResponse(f'<script>alert("登录成功");location.href="' + url + '" </script>')
        else:
            return HttpResponse(f'<script>alert("密码错误!");history.go(-1); </script>')

#用户注册
def userregister(request):
    if request.method=='GET':
        return render(request, 'mybook/register.html')
    elif request.method=='POST':
        #接收表单
        # data=request.POST.dict()
        data={}
        data['phone']=request.POST.get('phone')
        data['password']=request.POST.get('password')

        # 删除token
        # data.pop('csrfmiddlewaretoken')
        #从session中获取phone以及vcode
        sessions=request.session.get('vcodes')
        phone = sessions['phone']
        vcode = sessions['vcode']
        #验证手机号以及验证码
        if data['phone']!=phone and data['vcode']!=vcode:
            return HttpResponse(f'<script>alert("手机号码或验证码有错误!");history.back(); </script>')
        # 密码加密
        data['password'] = make_password(data['password'])
        #存入数据库
        obj=models.Users(**data)
        obj.save()
        #注册成功跳转到登陆页面
        url = reverse('mybook_login')
        return HttpResponse(f'<script>alert("注册成功");location.href="' + url + '" </script>')

#用户退出
def userexit(request):
    # flush删除当前会话数据
    #删除单个session del request.session['a'] 不存在就报错
    #清除所有会话session 但不会删除数据库数据 request.session.clear()
    #清除当前的会话数据 数据库也会删除request.session.flush()
    request.session.flush()
    url = reverse('mybook_index')
    return HttpResponse(f'<script>alert("退出成功");location.href="' + url + '" </script>')

#手机号验证
def checkphone(request):
    #接收
    phone=request.GET.get('phone')
    #验证
    obj=models.Users.objects.filter(phone=phone).count()
    #判断
    if obj:
        return JsonResponse({'code':1,'msg':'手机号码已存在'})
    else:
        return JsonResponse({'code': 0, 'msg': '手机号码可以使用'})

#短信验证码
def sendcoke(request):
    # 接收
    phone = request.GET.get('phone')
    #查看手机号码是否已经注册(二次验证码手机号码是否存在)
    obj = models.Users.objects.filter(phone=phone).count()
    # 判断手机号是否存在
    if obj:
        return JsonResponse({'code': 1, 'msg': '手机号码已存在','vcode':''})
    #创建一个验证码vcode
    vcode=random.randint(10000,99999)
    #存入session 注册操作时候进行验证
    request.session['vcodes']={'phone':phone,'vcode':123456}
    #调用发送短信方法
    # res=coke(phone,vcode)
    if True:
        return JsonResponse({'code': 0, 'msg': '短信验证码已发送!', 'vcode': 123456})
    # else:
    #     return JsonResponse({'code': 2, 'msg': '短信验证码发送失败,请重试', 'vcode': ''})



#封装发送短信验证码请求以及响应接收
# def coke(phone,vcode):
#     #请求时的POST数据
#     url='https://open.ucpaas.com/ol/sms/sendsms'
#     data={
#         "PhoneNumbers":phone,
#         "SignName":"阿里云短信测试",
#         "TemplateCode":"测试专用模板",
#         "param":vcode,
#         "mobile":phone
#     }
#     headers={
#         'Content-Type':'application/json'
#     }
#
#     #发送请求
#     response=requests.post(url,json=data,headers=headers)
#     #接收响应
#     res = response.json()
#     #响应格式     示例{"code":"0",
#     #    "msg":"OK",
#     #    "count":"1",
#     #    "create_date":"2017-08-28 19:08:28",
#     #    "uid":"",
#     #    "smsid":"f96f79240e372587e9284cd580d8f953",
#     #    "mobile":"18011984299"
#     #       }
#     #对code和msg进行判断 看短信是否发送成功
#     if res['code']=='000000' and res['msg']=='OK':
#         return True
#     else:
#         return False

templates/mybook/index.html
{% extends 'mybook/base1.html' %}
{% block base1 %}
    <div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>

		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for i in data  %}
                <li><a href="#{{ i }}" >{{ i.typename }}</a></li>
            {% endfor %}
{#			<li><a href="#model01" >小说类型图书</a></li>#}
{#			<li><a href="#model02" >历史类型图书</a></li>#}
{#			<li><a href="#model03" >保健养生类型图书</a></li>#}
{#			<li><a href="#model04" >教育类型图书</a></li>#}
{#			<li><a href="#model05" >小说类型图书</a></li>#}
{#			<li><a href="#model06" >小说类型图书</a></li>#}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="../../static/mybook/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="../../static/mybook/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="../../static/mybook/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="../../static/mybook/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="../../static/mybook/images/adv01.jpg"></a>
			<a href="#"><img src="../../static/mybook/images/adv02.jpg"></a>
		</div>
	</div>
    {% for i in data %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="{{ i }}">{{ i.typename }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for y in i.data_son %}
                    <a href="{% url 'mybook_list' %}?typeid={{ y.id }}">{{ y.typename }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'mybook_list' %}?typeid={{ i.id }}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>


		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="../../static/mybook/images/banner0{{ forloop.counter }}.jpg"></div>
			<ul class="goods_list fl">
                {% for z in i.books_set.all %}
                {% if forloop.counter < 5 %}
                <li>
					<h4><a href="#">{{ z.bkname }}</a></h4>
					<a href="{% url 'mybook_info' %}?id={{ z.id }}"><img src="{{ z.booksimgs_set.first.imgurl }}"></a>
					<div class="prize">¥{{ z.bkprice }}</div>
				</li>
                {% endif %}
                {% endfor %}
			</ul>
		</div>
	    </div>

    {% endfor %}
{% endblock %}

templates/mybook/submitorder.html
{% extends 'mybook/base1.html' %}
{% block base1 %}
<h3 class="common_title">确认收货地址</h3>
    <form method="post" action="{% url 'mybook_suborder' %}">
    {% csrf_token %}
	<div class="common_list_con clearfix">
        {% for i in receaddress %}
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" value="{{ i.id }}" name="receid" {% if i.receselect == 1 %}checked{% endif %}  }>{{ i.receaddress}} （{{ i.recename }} 收） 手机号:{{ i.recephone}}</dd>
		</dl>
        {% endfor %}
	</div>

	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" value="0" name="paymethod" checked>
			<label class="cash">货到付款</label>
			<input type="radio" value="1" name="paymethod">
			<label class="weixin">微信支付</label>
			<input type="radio" value="2" name="paymethod">
			<label class="zhifubao"></label>
			<input type="radio" value="3" name="paymethod">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>

	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品作者</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
        {% for i in data %}
            <ul class="goods_list_td clearfix">
                <li class="col01">1</li>
                <li class="col02"><img src="{{ i.bid.booksimgs_set.first.imgurl }}"></li>
                <li class="col03">{{ i.bid.bkname }}</li>
                <li class="col04">{{ i.bid.bkauthor }}</li>
                <li class="col05">{{ i.bid.bkprice}}</li>
                <li class="col06">{{ i.number }}</li>
                {% load pagetag %}
                <li class="col07">{% chengjfa i.number i.bid.bkprice %}</li>
            </ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ data.count }}</em>件商品，总金额<b>{{ countprice}}</b></div>
			<div class="transit">运费：<b>包邮</b></div>
			<div class="total_pay">实付款：<b>{{countprice}}</b></div>
		</div>
	</div>
    <input type="hidden" name="price"  value="{{ countprice }}">
	<div class="order_submit clearfix">
        <button type="submit"><a id="order_btn">提交订单</a></button>
	</div>
    </form>
{% endblock %}

templates/mybook/user_center_info.html
{% extends 'mybook/base1.html' %}
{% block base1 %}
<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="../../static/mybook/images/logo02.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
	</div>
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'mybook_usercenterinfo' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'mybook_orderlist' %}">· 全部订单</a></li>
				<li><a href="{% url 'mybook_receaddress' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>手机号：</span>{{ data.phone }}</li>
							<li><span>昵称：</span>{{ data.nikename }}</li>
							<li><span>联系地址：</span>{{ data.homeaddress }}</li>
						</ul>
				</div>
		</div>
		</div>
	</div>
{% endblock %}

templates/mybook/user_center_order.html
{% extends 'mybook/base1.html' %}
{% block base1 %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="../../static/mybook/images/logo02.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'mybook_usercenterinfo' %}">· 个人信息</a></li>
				<li><a href="{% url 'mybook_orderlist' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'mybook_receaddress' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for i in data %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ i.ordertime }}</li>
					<li class="col02">订单号：{{ i.id }}</li>
					<li class="col02 stress">
                        {% if i.state == 0 %}
                            未支付
                        {% elif i.state == 1 %}
                            已支付
                        {% elif i.state == 2 %}
                            已发货
                        {% elif i.state == 3 %}
                            已收货
                        {% elif i.state == 4 %}
                            已取消
                        {% endif %}
                    </li>
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for y in i.orderinfo_set.all %}
                                <ul class="order_goods_list clearfix">
									<li class="col01"><img src="{{ y.bid.booksimgs_set.first.imgurl }}"></li>
									<li class="col02">{{ y.bid.bkname }}<em>{{ y.bid.bkprice }}</em></li>
									<li class="col03">{{ y.number }}</li>
									<li class="col04">{{ y.price }}</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ i.countprice}}</td>
							<td width="15%">
                                {% if i.state == 0 %}
                                    未支付
                                {% elif i.state == 1 %}
                                    已支付
                                {% elif i.state == 2 %}
                                    已发货
                                {% elif i.state == 3 %}
                                    已收货
                                {% elif i.state == 4 %}
                                    已取消
                                {% endif %}
                            </td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				{% endfor %}

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>

{% endblock %}